In [102]:
from PIL import Image
import os
import numpy as np
import pandas as pd
import csv
from sklearn.preprocessing import LabelEncoder

In [83]:
alex_images_path = "Alex_Kelly_Pics/Alex"
kelly_images_path = "Alex_Kelly_Pics/Kelly"
test_images_path = "Alex_Kelly_Pics/TestSet"
image_labels_path = "Kelly_and_Alex_Image_Labels - Sheet1.csv"

In [3]:
def sorted_image_names(path):
    return sorted(os.listdir(path), key=lambda x: int(''.join(filter(str.isdigit, x))))

In [4]:
alex_image_names = sorted_image_names(alex_images_path)
kelly_image_names = sorted_image_names(kelly_images_path)
test_image_names = sorted_image_names(test_images_path)

image_names = alex_image_names + kelly_image_names

array([3, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 1, 0, 0, 0, 1, 1, 3, 3, 1, 1, 1, 3, 3, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 3, 1, 3, 3, 3, 0, 0, 3, 1, 1, 3, 3, 3, 3, 0, 1,
       1, 0, 0, 0, 1, 3, 3, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 0, 3, 3, 1, 1, 0, 0, 0, 0, 0, 3, 1, 1, 0, 1, 1, 1, 1,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 1, 3, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 1, 0, 2, 0, 1, 1, 0, 1, 3, 1, 2, 1, 3, 3, 0,
       3, 1, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 3, 1, 1,

In [106]:
labels = pd.read_csv(image_labels_path)
le = LabelEncoder().fit(labels["Landscape"])
labels["Landscape"] = le.transform(labels["Landscape"])
labels

image_name  Human  Castle  Indoors  Landscape  Woman  Daytime  \
0      Alex-Image01.png    1.0     0.0      0.0          3    0.0      1.0   
1      Alex-Image02.png    1.0     0.0      0.0          3    0.0      1.0   
2      Alex-Image03.png    0.0     0.0      0.0          0    0.0      1.0   
3      Alex-Image04.png    0.0     0.0      0.0          1    0.0      1.0   
4      Alex-Image05.png    0.0     0.0      0.0          1    0.0      1.0   
..                  ...    ...     ...      ...        ...    ...      ...   
480  Kelly-Image225.png    0.0     0.0      0.0          1    0.0      1.0   
481  Kelly-Image226.png    0.0     0.0      0.0          1    0.0      0.0   
482  Kelly-Image227.png    1.0     0.0      1.0          0    0.0      0.0   
483  Kelly-Image228.png    1.0     0.0      0.0          0    0.0      1.0   
484  Kelly-Image229.png    1.0     0.0      1.0          0    1.0      0.0   

     Children  Sunset  Flower  Animal  Building  Mask  Gray-Hair  Fire  \
0         1.0     0.0     0.0     1.0       0.0   0.0        0.0   0.0   
1         1.0     0.0     0.0     0.0       1.0   0.0        0.0   0.0   
2         0.0     0.0     0.0     0.0       1.0   0.0        0.0   0.0   
3         0.0     0.0     0.0     0.0       0.0   0.0        0.0   0.0   
4         0.0     0.0     0.0     0.0       0.0   0.0        0.0   0.0   
..        ...     ...     ...     ...       ...   ...        ...   ...   
480       0.0     0.0     1.0     1.0       0.0   0.0        0.0   0.0   
481       0.0     1.0     1.0     0.0       0.0   0.0        0.0   0.0   
482       0.0     0.0     0.0     1.0       1.0   0.0        0.0   0.0   
483       0.0     0.0     0.0     0.0       1.0   0.0        0.0   0.0   
484       0.0     0.0     0.0     0.0       1.0   0.0        0.0   0.0   

     Food_drink  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0  
..          ...  
480         0.0  
481         0.0  
482         0.0  
483         0.0  
484         0.0  

[485 rows x 16 columns]

In [91]:
def get_largest_size(folder):
    biggest_image = [0, 0]
    for filename in os.listdir(folder):
        img = Image.open(os.path.join(folder, filename))
        if img.size[0] > biggest_image[0]: 
            biggest_image[0] = img.size[0]
        if img.size[1] > biggest_image[1]:
            biggest_image[1] = img.size[1]
    return biggest_image

In [92]:
alex_im_size = get_largest_size(alex_images_path)
kelly_im_size = get_largest_size(kelly_images_path)
test_im_size = get_largest_size(test_images_path)

print("Max Image Sizes:", max(alex_im_size, kelly_im_size, test_im_size))

Max Image Sizes: [667, 400]


In [94]:
alex_image_names[0]

'Alex-Image01.png'

In [108]:
labels[labels["image_name"] == 'Alex-Image01.png'].drop("image_name", axis = 1).to_numpy()

array([[1., 0., 0., 3., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [109]:
def load_images_from_folder(folder, resize_shape=(700, 440)):
    images = []
    image_names = []
    count = 0
    for filename in os.listdir(folder):
        count += 1
        img = Image.open(os.path.join(folder, filename)).convert('RGB')
        img = img.resize(resize_shape)
        if img is not None:
            img_array = np.array(img)
            img_array = img_array.flatten()
            attr = labels[labels["image_name"] == filename].drop("image_name", axis = 1).to_numpy()
            img_array.append(attr)
            images.append(img_array)
            
        if count % int(len(os.listdir(folder)) / 10) == 0:
            print(f"{count / len(os.listdir(folder))*100}% Complete")
    return images

In [ ]:
np.ndarray.

In [110]:
load_images_from_folder(kelly_images_path)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [70]:
alex_images = load_images_from_folder(alex_images_path)
kelly_images = load_images_from_folder(kelly_images_path)
test_images = load_images_from_folder(test_images_path)

9.765625% Complete
19.53125% Complete
29.296875% Complete
39.0625% Complete
48.828125% Complete
58.59375% Complete
68.359375% Complete
78.125% Complete
87.890625% Complete
97.65625% Complete
9.606986899563319% Complete
19.213973799126638% Complete
28.82096069868996% Complete
38.427947598253276% Complete
48.03493449781659% Complete
57.64192139737992% Complete
67.24890829694323% Complete
76.85589519650655% Complete
86.46288209606988% Complete
96.06986899563319% Complete
10.0% Complete
20.0% Complete
30.0% Complete
40.0% Complete
50.0% Complete
60.0% Complete
70.0% Complete
80.0% Complete
90.0% Complete
100.0% Complete


In [73]:
merged_dataset = np.concatenate([alex_images, kelly_images])
merged_dataset

array([[103, 115, 126, ..., 123, 148,  61],
       [118,  96,  79, ...,  14,  13,  10],
       [160, 171, 182, ...,  50,  63,  74],
       ...,
       [192, 190, 177, ...,  23,  23,  23],
       [114, 150, 210, ...,  82,  78,  79],
       [225, 241, 253, ...,  50,  42,  76]], dtype=uint8)

In [ ]:
# Not sure this is going to work
# alex_images_df = pd.DataFrame(alex_images, index=alex_image_names)
# kelly_images_df = pd.DataFrame(kelly_images, index=kelly_image_names)
# test_images_df = pd.DataFrame(test_images, index=test_image_names)

In [ ]:
# alex_kelly_images_df = pd.concat([alex_images_df, kelly_images_df])
# alex_kelly_images_df.head(5)